fix waiting for toolbox pod to start

diff --git a/cephpod b/cephpod
--- a/cephpod
+++ b/cephpod
@@ -2,11 +2,17 @@
 ceph_pod=$(oc -n openshift-storage get pod | awk '/tools/{print $1}')
 if [ -z "$ceph_pod" ] ; then
   oc create -f ~/toolbox.yaml
-  sleep 5
-  ceph_pod=$(oc -n openshift-storage get pod | awk '/tools/{print $1}')
+  for n in `seq 0 3` ; do
+  	sleep 5
+  	ceph_pod=$(oc -n openshift-storage get pod | awk '/tools/&&/Running/{print $1}')
+	echo toolbox pod is $ceph_pod
+	if [ -n "$ceph_pod" ] ; then
+		break
+	fi
+  done
   if [ -z "$ceph_pod" ] ; then
-     echo "could not start ceph toolbox pod"
-     exit 1
+     	echo "could not start ceph toolbox pod"
+     	exit 1
   fi
 fi
 oc -n openshift-storage rsh $ceph_pod ceph $*
